nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - phpfpm
  volumes:
    - ./.docker/logs/access.log:/var/log/nginx/access.log
    - ./.docker/logs/error.log:/var/log/nginx/error.log
    - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
    - ./.docker/nginx/localhost.key:/etc/ssl/private/localhost.key
    - .:/var/www/html

phpfpm:
  build: ./.docker/php
  ports:
    - "9000:9000"
  links:
    - mysql
  volumes:
    - .:/var/www/html

mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./.docker/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    MYSQL_DATABASE: ${DB_DATABASE}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 8080:80
  environment:
    PMA_HOST: mysql
    PMA_USER: ${DB_USERNAME}
    PMA_PASSWORD: ${DB_PASSWORD}
    PMA_ARBITRARY: 1
